/* 
Jamie Huang, jhuan131
Alexey Solganik, asolgan1
Zach Zhou, zzhou43 
*/


DROP TABLE IF EXISTS CovidData;
DROP TABLE IF EXISTS AnnualCountryData;
DROP TABLE IF EXISTS AnnualEconData;
DROP TABLE IF EXISTS Country;
DROP PROCEDURE IF EXISTS GetCountryData;
DROP PROCEDURE IF EXISTS GetAllCountriesSortedBy;
DROP PROCEDURE IF EXISTS GetAnnualData;
DROP PROCEDURE IF EXISTS GetAllAnnualDataSortedBy;
DROP PROCEDURE IF EXISTS GetCovidData;
DROP PROCEDURE IF EXISTS UpsertCountryTuple;
DROP PROCEDURE IF EXISTS UpsertCovidDataTuple;
DROP PROCEDURE IF EXISTS UpsertAnnualCountryDataTuple;
DROP PROCEDURE IF EXISTS UpsertAnnualEconDataTuple;
DROP PROCEDURE IF EXISTS DeleteCountryTuple;
DROP PROCEDURE IF EXISTS DeleteCovidDataTuple;
DROP PROCEDURE IF EXISTS DeleteAnnualCountryDataTuple;
DROP PROCEDURE IF EXISTS DeleteAnnualEconDataTuple;
DROP PROCEDURE IF EXISTS TopCountries;
DROP PROCEDURE IF EXISTS LowVaxRate;
DROP PROCEDURE IF EXISTS EmploymentRate;
DROP PROCEDURE IF EXISTS GetCPIAboveCovidCases;
DROP PROCEDURE IF EXISTS GDPAboveAndBelow;
DROP PROCEDURE IF EXISTS NetLbRange;
DROP PROCEDURE IF EXISTS ShowGDPGrowth;